import { virtualSearchSelection } from "../lib/virtual-care";
import assert from "node:assert/strict";
import { adminDeliveryData } from "../lib/admin-delivery";
const form = new FormData();
form.set("telehealthMode", "Virtual only");
assert.ok(adminDeliveryData("continued_care", form).error);
form.append("statesServed", "Pennsylvania");
form.append("statesServed", "Pennsylvania");
form.set("programmingTimeZone", "America/New_York");
form.set("hoursOfOperation", "Evenings");
form.set("insuranceNotes", "Varies by state");
const result = adminDeliveryData("continued_care", form);
assert.equal(result.error, null);
assert.deepEqual(result.data.statesServed, ["Pennsylvania"]);
assert.equal(result.data.latitude, null);
assert.equal(result.data.publicCity, "");
assert.equal(result.data.totalBeds, null);
assert.equal(result.data.hoursOfOperation, "Evenings");
assert.equal(result.data.insuranceNotes, "Varies by state");
form.append("statesServed", "Invalid");
assert.ok(adminDeliveryData("continued_care", form).error);
form.set("telehealthMode", "In-person only");
assert.deepEqual(adminDeliveryData("continued_care", form).data.statesServed, []);
assert.equal(adminDeliveryData("sober_living", form).virtual, false);
console.log("Admin delivery validation checks passed.");

assert.deepEqual(virtualSearchSelection(undefined, "Pennsylvania"), { delivery: "virtual", virtualState: "Pennsylvania", virtualSearch: true });
assert.deepEqual(virtualSearchSelection("in-person", "Pennsylvania"), { delivery: "in-person", virtualState: undefined, virtualSearch: false });
assert.equal(virtualSearchSelection(undefined, "invalid").virtualSearch, false);
assert.equal(virtualSearchSelection("virtual").virtualSearch, true);
console.log("Search delivery and coverage selection checks passed.");
