import { strict as assert } from "node:assert";
import { OrganizationType, SubscriptionStatus } from "@prisma/client";
import { hasReferentAccess, canStartReferentTrial, trialEndFrom, trialDaysRemaining } from "../lib/referent-trial";
import { referentEnrollmentData, referentStepThreeSchema } from "../lib/referent-onboarding";
import { canSubmitReferrals, canUseInAppMessaging, canReceiveDirectReferrals } from "../lib/feature-gates";
const now = new Date("2026-09-22T12:00:00Z");
const trial = referentEnrollmentData({enrollmentChoice: "trial", billingCycle: "annual"}, now);
assert.equal(trial.subscriptionPlan, "professional");
assert.equal(trial.subscriptionBillingCycle, null);
assert.equal(trial.referentTrialEndsAt?.toISOString(), "2026-10-22T12:00:00.000Z");
assert.equal(hasReferentAccess(trial, now), true);
assert.equal(hasReferentAccess(trial, trial.referentTrialEndsAt!), false);
assert.equal(hasReferentAccess({...trial, referentTrialEndsAt: null}, now), false);
assert.equal(trialDaysRemaining(trial.referentTrialEndsAt!, now), 30);
assert.equal(trialDaysRemaining(now, trial.referentTrialEndsAt!), 0);
assert.equal(canStartReferentTrial(trial), false);
for (const plan of ["starter", "professional"]) {
  const paid = referentEnrollmentData({enrollmentChoice: plan, billingCycle: "annual"}, now);
  assert.equal(paid.subscriptionStatus, "incomplete");
  assert.equal(paid.subscriptionPlan, plan);
  assert.equal(paid.subscriptionBillingCycle, "annual");
  assert.equal(paid.referentTrialStartedAt, null);
  assert.equal(hasReferentAccess(paid, now), false);
  assert.equal(canStartReferentTrial(paid), true);
  assert.equal(canStartReferentTrial({...paid, stripeSubscriptionId: "sub_existing"}), false);
  assert.equal(canStartReferentTrial({...paid, referentTrialStartedAt: now}), false);
}
for (const choice of [undefined, "enterprise", "free", ""]) assert.equal(referentStepThreeSchema.safeParse({enrollmentChoice: choice}).success, false);
assert.equal(referentStepThreeSchema.safeParse({selectedPlan: "professional"}).success, false);
const future = trialEndFrom(new Date());
const org = {type: OrganizationType.referent, subscriptionPlan: "professional", subscriptionStatus: SubscriptionStatus.trialing, referentTrialEndsAt: future};
assert.equal(canSubmitReferrals(org), true);
assert.equal(canUseInAppMessaging(org), true);
assert.equal(canSubmitReferrals({...org, referentTrialEndsAt: new Date(0)}), false);
assert.equal(canUseInAppMessaging({...org, referentTrialEndsAt: new Date(0)}), false);
assert.equal(canSubmitReferrals({...org, subscriptionStatus: SubscriptionStatus.incomplete}), false);
assert.equal(canSubmitReferrals({...org, subscriptionStatus: SubscriptionStatus.active, referentTrialEndsAt: new Date(0)}), true);
assert.equal(hasReferentAccess({subscriptionStatus: null}), false);
assert.equal(canReceiveDirectReferrals({type: OrganizationType.aftercare_continued_care, subscriptionPlan: "professional", subscriptionStatus: SubscriptionStatus.trialing}), true);
console.log("Referent enrollment, payment gating, trial expiry, eligibility, and aftercare regression checks passed.");
